### ISSUE TITLE
New coc error ENOENT no such file or directory

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#151]
```
[coc.nvim] error: internal/bootstrap/switches/does_own_process_state.js:129
    cachedCwd = rawMethods.cwd();
                           ^
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:6472:19)
    at new Workspace (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:24074:29)
    at Object.<anonymous> (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:25842:19)
    at __webpack_require__ (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:23868:45)
    at __webpack_require__ (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:23581:43)
    at __webpack_require__ (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/user/.dotfiles/config/nvim/plugged/coc.nvim/build/index.js:22925:48) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

**Comment by ajr-dev** [comment]
It was fixed when I updated the plugins.
